/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-main': '#282a36',
        'bg-card': '#2b2d33',
        'bg-editor': '#1e1e1e',
        'border-subtle': '#3e4149',
        'text-primary': '#e0e0e0',
        'text-secondary': '#9ca3af',
        'accent-purple': '#bd93f9',
        'btn-bg': '#4a4d55',
        'btn-hover': '#374151',
        // DockerOpt Kinetic (Stitch)
        "on-primary-fixed": "#00452d",
        "tertiary-dim": "#e79400",
        "surface-dim": "#0e0e0e",
        "error-dim": "#d7383b",
        "on-error": "#490006",
        "tertiary-fixed": "#f8a010",
        "tertiary-fixed-dim": "#e79400",
        "secondary-container": "#005ac2",
        "on-surface-variant": "#adaaaa",
        "inverse-surface": "#fcf9f8",
        "primary-fixed": "#69f6b8",
        "on-tertiary": "#573500",
        "primary": "#69f6b8",
        "error": "#ff716c",
        "inverse-on-surface": "#565555",
        "on-primary-fixed-variant": "#006544",
        "outline": "#767575",
        "surface-tint": "#69f6b8",
        "on-tertiary-container": "#4a2c00",
        "surface-container-low": "#131313",
        "background": "#0e0e0e",
        "on-secondary-fixed-variant": "#004da8",
        "primary-dim": "#58e7ab",
        "on-primary": "#005a3c",
        "surface-variant": "#262626",
        "outline-variant": "#484847",
        "primary-container": "#06b77f",
        "on-secondary-fixed": "#003271",
        "inverse-primary": "#006d4a",
        "surface-bright": "#2c2c2c",
        "tertiary-container": "#f8a010",
        "surface-container": "#1a1a1a",
        "secondary-fixed-dim": "#a9c4ff",
        "surface": "#0e0e0e",
        "secondary-fixed": "#bfd1ff",
        "tertiary": "#ffb148",
        "on-secondary-container": "#f7f7ff",
        "on-surface": "#ffffff",
        "secondary": "#699cff",
        "surface-container-highest": "#262626",
        "on-error-container": "#ffa8a3",
        "surface-container-high": "#20201f",
        "on-primary-container": "#002919",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#58e7ab",
        "on-tertiary-fixed": "#2a1700",
        "on-background": "#ffffff",
        "secondary-dim": "#699cff",
        "on-tertiary-fixed-variant": "#563400",
        "on-secondary": "#001e4a",
        "error-container": "#9f0519",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono: ['Fira Code', 'JetBrains Mono', 'Menlo', 'Monaco', 'Courier New', 'monospace'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-subtle': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(189, 147, 249, 0)' },
          '50%': { boxShadow: '0 0 0 4px rgba(189, 147, 249, 0.3)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out',
        'pulse-subtle': 'pulse-subtle 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
